services:
  db:
    image: mysql:9.3
    restart: always
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    expose:
      - 3306   
volumes:
  db_data:
secrets:
  db_password:
    file: secrets/db_password.txt