CREATE TABLE Acronyms (
  id                  INTEGER   PRIMARY KEY,
  acronym             TEXT      NOT NULL,
  caseSensitive       BOOLEAN   NOT NULL CHECK (caseSensitive IN (0, 1)),
  explanation         TEXT      NOT NULL,
  isChannelRestricted BOOLEAN   NOT NULL DEFAULT 0 CHECK (isChannelRestricted IN (0, 1));
);

CREATE UNIQUE INDEX acronym ON Acronyms(acronym);

INSERT INTO Acronyms
  (acronym, caseSensitive, explanation)
VALUES
  ('TSIMFD', 0, 'https://www.youtube.com/watch?v=b-CvLWbfZhU', 1),
  ('FIRST', 1, 'For Inspiration and Recognition of Science and Technology', 0),
  ('FRC', 0, '*FIRST* Robotics Competition', 0),
  ('FTC', 0, '*FIRST* Tech Challenge', 0),
  ('FLL', 0, '*FIRST* LEGO League', 0),
  ('FYSA', 0, 'for your situational awareness', 0),
  ('WPI', 0, 'Worcester Polytechnic Institute', 0),
  ('CTRE', 0, 'Cross the Road Electronics', 0),
  ('CTR', 0, 'Cross the Road Electronics', 0),
  ('CSA', 0, 'Control System Advisor', 0),
  ('FTAA', 0, '*FIRST* Technical Advisor Assistant', 0),
  ('FTA', 0, '*FIRST* Technical Advisor', 0),
  ('GA', 0, 'Game Announcer', 0),
  ('MC', 0, 'Emcee', 0),
  ('RI', 0, 'Robot Inspector', 0),
  ('LRI', 0, 'Lead Robot Inspector', 0),
  ('JA', 0, 'Judge Advisor', 0),
  ('JAA', 0, 'Judge Advisor Assistant', 0),
  ('VC', 0, 'Volunteer Coordinator', 0),
  ('WTA', 0, 'Wi-Fi Technical Advisor', 0),
  ('PDP', 0, 'Program Delivery Partner or the Power Distribution Panel (CTRE <https://store.ctr-electronics.com/power-distribution-panel/>)', 0),
  ('PDH', 0, 'Power Distribution Hub (REV <https://www.revrobotics.com/rev-11-1850/>)', 0),
  ('PCM', 0, 'Pneumatic Control Module (CTRE <https://store.ctr-electronics.com/pneumatic-control-module/>)', 0),
  ('PH', 0, 'Pneumatic Hub (REV <https://www.revrobotics.com/rev-11-1852/>)', 0),
  ('VRM', 0, 'Voltage Regulator Module (CTRE <https://store.ctr-electronics.com/voltage-regulator-module/>)', 0),
  ('RPM', 0, 'Revolutions per minute or the Radio Power Module (REV <https://www.revrobotics.com/rev-11-1856/>)', 0),
  ('GP', 0, 'Gracious Professionalism', 0),
  ('TBA', 0, 'The Blue Alliance (or To Be Announced)', 0),
  ('KOP', 0, 'Kit of Parts <https://www.firstinspires.org/robotics/frc/kit-of-parts>', 0),
  ('TBD', 0, 'To Be Determined', 0),
  ('GDC', 0, 'Game Design Committee', 0),
  ('CAD', 0, 'Computer Aided Design', 0),
  ('WFA', 0, 'Woodie Flowers Award', 0),
  ('WFFA', 0, 'Woodie Flowers Finalist Award', 0),
  ('DLA', 0, "Dean's List Award", 0),
  ('FIA', 0, '*FIRST* Impact Award or *FIRST* in Alabama', 0),
  ('COTS', 0, 'Commercial Off The Shelf', 0),
  ('HR', 0, 'Head Referee', 0),
  ('HOF', 0, 'Hall of Fame', 0),
  ('RTFM', 0, 'Read the *FIRST* Manual', 0),
  ('YMMV', 0, 'Your Mileage May Vary', 0),
  ('PWM', 0, 'Pulse Width Modulation', 0),
  ('DOA', 0, 'Dead On Arrival', 0),
  ('EI', 0, 'Engineering Inspiration (Award)', 0),
  ('RD', 0, 'Regional Director', 0),
  ('FSM', 0, '*FIRST* Senior Mentor', 0),
  ('BOM', 0, 'Bill of Materials', 0),
  ('CAN', 0, 'Controller Area Network', 0),
  ('STIMS', 0, 'Student Team Information Management System (<https://my.firstinspires.org/Dashboard/>)', 0),
  ('VMS', 0, 'Volunteer Management System (<https://my.firstinspires.org/VMS/Login.aspx>)', 0),
  ('OPR', 0, 'Offensive Power Rating (<https://www.statbotics.io/blog/models>)', 0),
  ('EPA', 0, 'Expected Points Added (<https://www.statbotics.io/blog/models>)', 0)
;