name: Production

on:
    workflow_run:
        workflows: ["Test"]
        types: [completed]
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
        - name: Deploy to Production
          uses: appleboy/ssh-action@v1.0.3
          with:
              host: ${{ secrets.PRODUCTION_HOSTNAME }}
              username: ${{ secrets.PRODUCTION_USERNAME }}
              key: ${{ secrets.PRIVATE_KEY }}
              port: 22
              script_stop: true
              script: |
                cd ~/first-discord-bot
                git fetch --all
                git reset --hard origin/main 
                ~/.nvm/versions/node/v20.12.2/bin/pm2 stop first-discord-bot
                ~/.nvm/versions/node/v20.12.2/bin/npm ci --cache .npm
                ~/.nvm/versions/node/v20.12.2/bin/pm2 restart first-discord-bot
